"""Chunk 5 (final) of the weight>=10 batch (indices 600-822). Same mechanism as
chunk1-4."""
import json
import os
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BATCH = json.load(open(os.path.join(ROOT, "outputs", "phase5-batch-2026-09-26-w10.json")))

DECISIONS = [
    (600, "assoc", "Dan 3:5/3:7 show worship triggered by instrument sounds including the flute, matching the Adore/Cornet pattern."),
    (601, "assoc", "Dan 3:5/3:7 show worship triggered by instrument sounds including the sackbut, matching the same pattern."),
    (602, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (603, "assoc", "Ezek 23:32/35:15 use the 'cup' of judgment poured on Edom metaphorically — a poetic image, not hierarchy."),
    (604, "assoc", "Dan 10:13/12:1 use governor and (angelic) prince as near-synonymous authority titles in different registers."),
    (605, "assoc", "Deut 17:3/4:19 warn against astral worship generally without a specific heaven-sun hierarchy in the cited text, matching Heaven/Moon."),
    (606, "assoc", "Gen 1:30/Ps 104:14 show God providing herbs for animals — a thematic providence claim, not hierarchy."),
    (607, "assoc", "Amos 5:8/Job 9:9 name a constellation — category mismatch with the field of astronomy, matching Astronomy/Orion."),
    (608, "assoc", "Ezek 29:3/Isa 27:1 use dragon and whale/Leviathan as near-synonymous sea-monster terms, siblings."),
    (609, "assoc", "Gen 4:2/Exod 3:1 (Abel's occupation; Moses shepherding) — different unrelated narratives, no clean agriculture-desert relation."),
    (610, "narrower:b", "Gen 31:27/4:21 don't name 'organ' directly, but Easton's own Music,Instrumental catalog lists it among instruments, matching the established instrument-catalog pattern."),
    (611, "narrower:b", "2 Sam 6:5/Dan 3:7 name psaltery as one instrument within the broader practice of music, matching the Harp/Music pattern."),
    (612, "assoc", "1 Chr 20:4/2 Sam 21:15 (Philistine wars mentioning giants) — the book narrates this content, not a hierarchy."),
    (613, "assoc", "Jer 49:16/Song 2:14 show doves nesting in rock-clefts near caves — habitat co-occurrence, not hierarchy."),
    (614, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (615, "assoc", "Gen 9:21/Prov 20:1 (Noah's drunkenness; a proverb on wine) — no direct tent-wine relation in the cited text."),
    (616, "assoc", "Gen 10:5/Ps 72:10 (maritime peoples; Sheba's tribute) — coordinate, not hierarchy."),
    (617, "assoc", "Gen 10:5/Ps 72:10 — same evidence, coordinate not hierarchy."),
    (618, "assoc", "Gen 10:14/Jer 47:4 show the Philistines as the subject of a judgment oracle — co-occurrence, not hierarchy."),
    (619, "assoc", "Deut 11:30/Gen 12:6 (mountains near Shechem; Abram's journey) — weak/general evidence, not a clear Canaan-plain containment claim."),
    (620, "assoc", "Gen 14:2/10:19 list Bela and Gomorrah as sibling cities of the plain, coordinate not hierarchy."),
    (621, "assoc", "Gen 14:2/10:19 list Bela and Zeboim as sibling cities, coordinate."),
    (622, "assoc", "1 Kgs 22:48/9:28 show merchants trading via ships to Ophir — a trade-route relation, not hierarchy."),
    (623, "assoc", "2 Kgs 23:12/Deut 22:8 use dwellings and house near-synonymously for habitation."),
    (624, "assoc", "Deut 11:30/Gen 12:6 — weak/general evidence, not a clear Gilgal-plain relation."),
    (625, "assoc", "Deut 11:30/Gen 12:6 — same weak evidence, not a clear Gilgal-grove relation."),
    (626, "assoc", "Deut 1:7/Josh 10:40 associate Amorites with hill country broadly in the cited text, not specifically 'plain.'"),
    (627, "assoc", "2 Kgs 15:29/2 Chr 16:4 (Tiglath-pileser's invasion; an unrelated Ben-hadad narrative) — no clean calf-plain relation."),
    (628, "assoc", "Gen 28:19/Hos 4:15 name Bethel and Gilgal as sibling Israelite worship-site references, coordinate."),
    (629, "assoc", "1 Chr 5:8 names a person Bela (a Reubenite), distinct from the city Bela/Zoar — person-in-territory, kept associated rather than asserting place-containment."),
    (630, "assoc", "Josh 13:27/11:2 place Gad's tribal territory near plain regions — tribe-in-territory, not a clean containment claim from this evidence."),
    (631, "assoc", "1 Sam 30:28/Josh 13:16 (Aroer's general territory) — evidence too general to assert clean geographic containment."),
    (632, "assoc", "Gen 25:23/17:4 (the Esau/Jacob birthright oracle; the Abrahamic covenant) — weak specific link between first-born and prophecy generally."),
    (633, "assoc", "Gen 13:18/18:1 (the oaks of Mamre near Hebron) — evidence doesn't specifically establish a Hebron-plain containment claim."),
    (634, "assoc", "Gen 13:18/23:2 show Sarah's death and mourning at Hebron — narrative co-occurrence, not hierarchy."),
    (635, "assoc", "Gen 36:20/Deut 2:22 place Anah among the Horite inhabitants of Seir — person-in-place, matching the established pattern."),
    (636, "assoc", "Gen 15:9/Lev 1:14 list pigeon and turtledove as a paired category of small sacrificial birds, coordinate not hierarchy."),
    (637, "assoc", "1 Kgs 6:1/Num 1:1 use the Exodus as a chronological anchor-point — a category relation (event vs. dating system) this vocabulary doesn't cleanly capture."),
    (638, "assoc", "Exod 3:8/Deut 1:7 (the deliverance promise; hill-country travel) — no direct prophecy-river relation in the cited text."),
    (639, "assoc", "Exod 23:31/Gen 15:18 (a border description; the covenant-boundary reference) — no direct desert-river relation established."),
    (640, "assoc", "Isa 9:7/16:5 (messianic increase; Moab's tent imagery) — unrelated oracles, no direct prophecy-tent relation."),
    (641, "narrower:a", "Ezek 44:7 ties uncircumcision explicitly to covenant-abomination — circumcision is the specific required sign within the broader covenant institution (Gen 17's own terms, reflected in this oracle's logic)."),
    (642, "assoc", "Gen 18:2/23:7 show bowing as a customary greeting gesture used toward both angelic visitors and ordinary people — a shared custom, not hierarchy."),
    (643, "assoc", "Ezek 38:22/Ps 11:6 use brimstone and the judgment 'cup' as parallel poetic images, not hierarchy."),
    (644, "assoc", "Gen 23:8/25:9 show Ephron's cave sold for burial — narrative/transactional co-occurrence, not hierarchy."),
    (645, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (646, "assoc", "Gen 25:9/35:29 show a cave used as a burial site — location-of-practice, matching the Burial/Gardens pattern."),
    (647, "assoc", "Exod 35:22/Num 31:50 list bracelets and earrings as coordinate jewelry types, siblings."),
    (648, "causes:b", "Ps 133:3 ties dew directly to fertility/blessing imagery, matching the established Rain-causes-Agriculture pattern."),
    (649, "causes:a", "Ezek 27:17/Deut 32:14 (agricultural trade goods; farm produce) support agriculture as what produces food, matching the Agriculture-causes-Wine pattern."),
    (650, "causes:b", "Gen 27:28/Zech 8:12 tie dew directly to the vine/seed yielding fruit, matching the Rain/Dew-causes-Agriculture pattern applied to corn specifically."),
    (651, "assoc", "1 Sam 19:13/Judg 18:17 show a bolster used to disguise teraphim in one specific narrative — object co-occurrence, not hierarchy."),
    (652, "assoc", "Gen 28:18/35:20 describe an idol-stone and a separate memorial pillar in different narratives — coordinate standing-stone uses, matching the Idol/Stone pattern."),
    (653, "assoc", "1 Sam 7:12/Josh 4:9 (Samuel's memorial stone; Joshua's stones at a different location) — weak/mismatched evidence for an idol-Shechem relation."),
    (654, "narrower:b", "Isa 60:6 names the dromedary as a specific one-humped type within the general camel category, alongside 2 Chr 9:1's camels."),
    (655, "assoc", "Exod 15:20/1 Sam 10:5 show dance and music as companion practices, matching the Dance/Music,Instrumental pattern."),
    (656, "assoc", "1 Sam 18:6/Exod 15:20 show women playing instruments in celebratory contexts — co-occurrence, not hierarchy."),
    (657, "assoc", "1 Chr 6:3/Exod 15:20 show Miriam playing an instrument — person-practice relation, matching the Asaph pattern."),
    (658, "assoc", "1 Sam 25:2/Job 1:3 show Nabal's business and cattle possessions at Carmel — person-place-possessions co-occurrence, not hierarchy."),
    (659, "assoc", "1 Sam 25:2/Job 1:3 — weak/unrelated evidence for a banquet-cattle relation specifically."),
    (660, "assoc", "1 Chr 2:19/2:50 record Hur descended through Ephrath's line — genealogical, not hierarchy."),
    (661, "narrower:b", "Gen 36:11 names Kenaz among the chiefs/clans of Edom (sons of Eliphaz), matching the Edom/Teman clan-chief pattern."),
    (662, "assoc", "Gen 36:15/Amos 1:12 list Kenaz and Teman as sibling clan-chiefs in Esau's lineage, coordinate not hierarchy between each other."),
    (663, "narrower:b", "Exod 15:15/Gen 36:15 name Teman among 'the chiefs of Edom,' a specific bearer of the general Duke/chief title."),
    (664, "assoc", "Amos 1:12/Jer 49:7 list Bozrah and Teman as sibling Edomite locations, coordinate not hierarchy between each other."),
    (665, "assoc", "2 Sam 1:24/Judg 5:30 mention embroidered/dyed garments descriptively — a decorative technique, not a clean part-of or causal composition claim."),
    (666, "assoc", "1 Kgs 10:10/Gen 43:11 list balm and myrrh as coordinate luxury/trade goods, siblings."),
    (667, "assoc", "1 Kgs 10:10/Gen 43:11 list balm and honey as coordinate trade goods."),
    (668, "assoc", "Gen 41:10/39:20 show a captain overseeing a dungeon — a role-place relation, not hierarchy."),
    (669, "assoc", "Gen 38:12/Judg 14:1 (Judah's wife's death; Samson's Timnah visit) — unrelated narratives, no clean sheep-Timnath relation."),
    (670, "narrower:b", "2 Kgs 4:42/Deut 32:14 list wheat among food items, matching the Food/Milk specific-food-type pattern."),
    (671, "assoc", "Ezek 16:11/Gen 41:42 (jewelry adornment; an unrelated Joseph narrative) — weak/unrelated link between chain and silk."),
    (672, "assoc", "Ezek 16:11/Gen 41:42 — same weak evidence, no clean chain-linen relation."),
    (673, "assoc", "Jer 51:57/Nah 1:10 show princes made drunk with wine — narrative detail, not hierarchy with 'governor.'"),
    (674, "assoc", "Exod 6:23/Num 2:3 place Amminadab within Judah's tribal context — membership relation, matching the Caleb/Judah,Tribe-of pattern."),
    (675, "assoc", "Gen 47:6/2 Chr 26:10 (Goshen settlement; unrelated wilderness towers) — no clean Goshen-plain relation established."),
    (676, "assoc", "Exod 3:8/3:17 (the deliverance promise repeated) — no direct Perizzites-wine relation in the cited text."),
    (677, "assoc", "Deut 32:6/Isa 63:16 invoke God as Father near a separate 'fear the LORD' context — thematic but not a clean father/fear-of-the-Lord hierarchy."),
    (678, "assoc", "Lev 10:1/Exod 28:1 show Nadab using a censer in his fatal offense — narrative object-person co-occurrence, not hierarchy."),
    (679, "assoc", "Exod 29:2/Num 6:15 both describe unleavened bread specifically — the cited evidence doesn't frame bread and leaven as a contrastive pair, so associated is the disciplined choice despite the well-known Passover unleavened/leavened distinction elsewhere."),
    (680, "assoc", "Exod 12:16/Num 29:1 show convocation as a recurring element across multiple distinct festivals rather than a narrower type of festival itself, matching how Convocation was treated relative to First-fruits/Pentecost/Tabernacles."),
    (681, "assoc", "2 Chr 30:5/35:18 record a Passover proclamation within Chronicles' narrative — the book covers the topic, not a hierarchy."),
    (682, "causes:a", "Ps 51:7's 'purify me with hyssop' directly ties the herb to the purification rite as its ritual instrument."),
    (683, "assoc", "Exod 15:7/Ps 83:13 use chaff and a whirling wheel/tumbleweed as parallel judgment-imagery similes, not hierarchy."),
    (684, "part_of:a", "2 Sam 6:5 describes instruments made of fir/cypress wood, matching the established wood-as-instrument-material pattern."),
    (685, "assoc", "1 Chr 23:29/Lev 7:9 show cakes baked in a pan — a container/instrument relation, matching the Cup/Wine pattern rather than composition."),
    (686, "assoc", "Deut 24:19/Lev 23:22 tie gleaning law to provision for foreigners, matching the Agriculture/Foreigner and Agriculture/Poor pattern."),
    (687, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (688, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (689, "assoc", "Num 35:16/Lev 24:17 discuss weapon-type and murder penalty generally — not a composition claim about the Murder concept via copper specifically."),
    (690, "assoc", "Deut 24:12/24:17 (a pledge-related sleeping law; foreigner-justice law) — adjacent but distinct legal topics, not a clean bed-loan hierarchy."),
    (691, "assoc", "Deut 12:6/Mal 3:8 mention firstborn-redemption and tithing as coordinate offering obligations in different contexts, not hierarchy."),
    (692, "assoc", "Exod 22:29/23:19 (firstfruits law; the kid-in-milk law) — coincidentally adjacent verses, no real first-fruits-kid relation."),
    (693, "assoc", "Lev 23:15/25:8 tie Pentecost's calculation to a seven-week count, matching the Sabbath/Seven calendrical pattern."),
    (694, "assoc", "1 Kgs 19:8/Deut 9:18 show fasting and prayer as companion spiritual practices, matching the Confession/Fast pattern."),
    (695, "assoc", "Exod 25:22/30:6 describe meeting God at the mercy-seat without the cited text naming 'propitiation' explicitly — associated avoids importing a theological term the given evidence doesn't use."),
    (696, "assoc", "The 'mount of the congregation' (a cosmic/mythological reference, Isa 14) and the tabernacle's mercy-seat are unrelated concepts linked only by an incidental shared-verse-chain artifact — correctly kept associated rather than asserting a real connection."),
    (697, "assoc", "Divination and the mercy-seat share no real thematic connection in the cited evidence — a mechanical co-reference artifact, correctly kept associated."),
    (698, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (699, "assoc", "1 Kgs 8:6/2 Sam 6:2 show the ark temporarily housed at Kirjath-jearim before Jerusalem — a location-of-residence relation, not composition."),
    (700, "assoc", "1 Kgs 7:50/Exod 27:3 use censer and firepan as overlapping/near-synonymous ritual-utensil terms, siblings."),
    (701, "assoc", "Exod 26:1/26:31 (tabernacle curtain colors; veil-making) — no specific evidence about doors and colour."),
    (702, "assoc", "Exod 27:3/Lev 16:12 use firepan and pan as overlapping utensil terms, siblings, matching the Censer/Firepan pattern."),
    (703, "assoc", "1 Kgs 7:16/Exod 38:17 name chapiter (capital) and fillets as sibling architectural components, neither clearly part of the other from the cited text."),
    (704, "assoc", "Jer 1:11 (Jeremiah's almond-rod vision) and Zech 4:2 (a separate lampstand vision) are two distinct, unrelated visions in the cited evidence — not establishing the almond-motif in lampstand design."),
    (705, "assoc", "Exod 27:21/Mal 2:7 show priests maintaining the candlestick — a role-object relation, not hierarchy."),
    (706, "assoc", "Exod 28:4/1 Sam 23:6 name the coat among high-priestly garments without establishing it as structurally part of the high priest (a person)."),
    (707, "assoc", "Exod 28:4/1 Sam 23:6 — same reasoning for the girdle."),
    (708, "assoc", "1 Sam 2:18/Lev 8:7 name ephod and mantle as distinct priestly garments, siblings."),
    (709, "assoc", "1 Sam 2:18/Exod 28:4 name ephod and mitre as distinct priestly garments, siblings."),
    (710, "assoc", "Exod 28:4/Isa 11:5 name coat and girdle as distinct garment items, siblings."),
    (711, "assoc", "Exod 28:31/28:4 name mantle and mitre as distinct priestly garments, siblings."),
    (712, "assoc", "Exod 28:17/Prov 31:10 list carbuncle and ruby among the breastplate's coordinate gemstones, siblings."),
    (713, "assoc", "Exod 28:17/Ezek 28:13 list ruby and topaz as coordinate gemstones."),
    (714, "assoc", "Exod 28:17/Ezek 28:13 list carbuncle and topaz as coordinate gemstones."),
    (715, "assoc", "Exod 28:18/Ezek 28:13 list chalcedony and sapphire as coordinate gemstones."),
    (716, "assoc", "1 Sam 2:28/2 Sam 12:7 (priesthood selection; Nathan's rebuke of David) — unrelated content, no evidence connecting the high priesthood to the Messiah title specifically."),
    (717, "assoc", "Exod 28:42/Lev 16:4 both discuss linen garments without a specific breeches-colour claim."),
    (718, "assoc", "Exod 29:13/Lev 9:19 don't establish a sheep-specific clean-status hierarchy beyond general sacrificial-fat context, matching Food/Sheep and Clean/Food."),
    (719, "assoc", "Weak/general evidence — no specific festivals-wine relation established, kept as the conservative default."),
    (720, "assoc", "Exod 29:40/16:36 use tenth-deal and drink-offering as coordinate technical offering-measurement terms, matching the Tenth-deal/Wine pattern."),
    (721, "assoc", "Exod 30:23/Jer 6:20 list calamus and frankincense as coordinate spice ingredients, siblings."),
    (722, "assoc", "Exod 30:23/Prov 7:17 list calamus and cinnamon as coordinate spice ingredients."),
    (723, "assoc", "Prov 7:17/Exod 30:23 list aloes and calamus as coordinate spice ingredients."),
    (724, "assoc", "Prov 7:17/Exod 30:23 list aloes and cinnamon as coordinate spice ingredients."),
    (725, "assoc", "Exod 30:23/Prov 7:17 list cinnamon and myrrh as coordinate spice ingredients."),
    (726, "assoc", "Num 24:6/Ps 45:8 list aloes and myrrh as coordinate fragrance ingredients."),
    (727, "assoc", "1 Kgs 12:28/Exod 32:8 show a golden calf (bullock) set up at Bethel — narrative/location-object co-occurrence, not hierarchy."),
    (728, "narrower:a", "2 Kgs 23:6/10:27 show the Asherah as a specific type of cultic idol-object torn down alongside other idols, matching the Golden-calf/Idol pattern."),
    (729, "assoc", "2 Chr 15:16/34:7 show groves and idols torn down together in cultic reform, matching the Idol/High-place co-occurrence pattern rather than a clean hierarchy."),
    (730, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (731, "assoc", "Exod 39:27/Isa 61:10 (priestly linen garments; a joy-poem) — no direct colour-poetry relation established."),
    (732, "assoc", "Lev 24:14/Josh 7:25 (camp-cursing law; Achan's stoning and burning) — unrelated legal and narrative content, no clean encamp-fire relation."),
    (733, "assoc", "Deut 14:15/Job 30:29 list cuckoo and owl among coordinate unclean/desolate birds, siblings."),
    (734, "assoc", "Deut 14:15/Job 30:29 list hawk and owl as coordinate unclean birds."),
    (735, "assoc", "Deut 14:15/Job 30:29 list night-hawk and owl as coordinate unclean birds."),
    (736, "assoc", "Isa 34:11/Zeph 2:14 list owl and pelican as coordinate desolate-place birds, siblings."),
    (737, "assoc", "Ps 102:6/Mic 1:8 use 'desert owl' as a poetic self-comparison — not a clean desert-broader-than-owl category relation."),
    (738, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (739, "narrower:b", "2 Sam 15:30/Ezek 24:17 (mourning-dress removal; a turban reference) support 'tires' (archaic for ornamental headwear) as a specific type of dress."),
    (740, "assoc", "2 Chr 33:6/Lev 20:2 (child sacrifice; a law about dedicated things) — the cited evidence doesn't actually involve Jephthah's vow, no real divination connection established."),
    (741, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (742, "assoc", "2 Chr 33:6/28:3 (occult practice; incense in the valley of Hinnom) — thematically adjacent but not a clean familiar-spirit/Gehenna hierarchy, matching the Divination/Gehenna call."),
    (743, "assoc", "Ps 98:6/2 Chr 29:27 use cornet and trumpets as distinct but related horn-instruments, siblings, each already independently placed under Music,Instrumental."),
    (744, "narrower:a", "Deut 27:15/Lev 26:1 treat the graven/carved image as a specific type within the general idol category, matching the Golden-calf/Idol and Asherah/Idol pattern."),
    (745, "assoc", "Jer 37:21/2 Kgs 25:3 (Jeremiah's bread ration; a famine notice) both occur under Zedekiah's reign — narrative co-occurrence, not hierarchy."),
    (746, "assoc", "Num 1:52/2:2 show banners organizing tribal encampments — co-occurring organizational elements, not hierarchy."),
    (747, "assoc", "Num 2:2/Isa 18:3 show camp organization and ensigns as co-occurring elements."),
    (748, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (749, "narrower:b", "Judg 1:16/1 Chr 2:55 connect the Rechabites' scribal family to Kenite ancestry — a specific clan within the broader Kenite people."),
    (750, "assoc", "Josh 14:6/15:17 record Kenaz as Caleb's brother/family — sibling/genealogical relation, not hierarchy."),
    (751, "assoc", "Josh 15:14/Judg 1:10 list Ahiman and Sheshai as sibling sons of Anak, each already independently narrower under Giants."),
    (752, "assoc", "Josh 15:14/Judg 1:10 list Ahiman and Talmai as sibling sons of Anak."),
    (753, "assoc", "Josh 15:14/Judg 1:10 list Sheshai and Talmai as sibling sons of Anak."),
    (754, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (755, "narrower:a", "1 Kgs 18:19/15:13 treat Baal-worship's images as a specific named form of idol, matching the Asherah/Idol and Golden-calf/Idol pattern."),
    (756, "assoc", "1 Chr 6:43/23:6 place Gershom in a Levitical genealogy near Merarite divisions — administrative/genealogical proximity, not hierarchy."),
    (757, "assoc", "2 Kgs 15:29/Num 32:1 discuss Aroer within Gadite territory generally — evidence too general for a clean city-category claim."),
    (758, "assoc", "Ps 92:12/1:3 use cedar and river-planted trees as parallel poetic flourishing images, not hierarchy."),
    (759, "assoc", "1 Kgs 4:13/Deut 4:43 — weak/general evidence, not a clear Bashan-plain containment claim."),
    (760, "assoc", "Jer 10:9/Isa 40:19 (hammered silver from Tarshish; the idol-casting process) — no specific evidence about idol coloring."),
    (761, "part_of:b", "Deut 12:5/2 Chr 7:12 describe the temple as the chosen sanctuary within Jerusalem, matching the established Jerusalem/Temple part_of pattern from an earlier chunk."),
    (762, "assoc", "Deut 12:15/14:5 list hart and roe deer as coordinate clean-animal types, siblings."),
    (763, "assoc", "Deut 29:18/Amos 6:12 pair gall and wormwood as coordinate bitterness metaphors, matching the Gall/Hemlock pattern."),
    (764, "assoc", "Job 34:6/6:4 use 'arrows of the Almighty' as an affliction metaphor — not specifically poison-tipped arrows in the cited text."),
    (765, "assoc", "Deut 33:17/1 Kgs 22:11 (a general horn-blessing image; Zedekiah's specific iron-horn prop) — a narrative object-person co-occurrence, not hierarchy."),
    (766, "assoc", "Ezek 16:15/20:8 use harlotry as near-synonymous with idolatry in the prophetic marriage-metaphor, an identity relation rather than one causing the other."),
    (767, "assoc", "1 Chr 18:4/Josh 11:6 (captured chariots; an unrelated battle-reassurance) — no direct chariot-fire relation in the cited text."),
    (768, "assoc", "1 Kgs 20:26/Josh 19:30 list Aphik and Rehob as neighboring cities, siblings."),
    (769, "assoc", "Josh 14:6/15:17 show Othniel son of Kenaz capturing Debir — person-place conquest narrative, not hierarchy."),
    (770, "narrower:b", "Job 1:6 places 'the accuser' (Satan) specifically among the 'sons of God' presenting themselves — a specific role within that broader angelic assembly."),
    (771, "assoc", "Dan 3:25/Job 1:6 reference an ambiguous divine figure and a separate heavenly-court scene in unrelated narratives — the evidence doesn't frame angel and devil as directly contrasted, so associated is the disciplined choice over an unearned contrasts claim."),
    (772, "assoc", "Isa 28:15/28:2 (a 'covenant with death' oracle; a separate 'mighty hand' oracle) — no direct covenant-hand relation established."),
    (773, "assoc", "Dan 9:3/Ezra 8:21 show confession and fasting as companion spiritual practices, matching the Fast/Prayer pattern."),
    (774, "assoc", "1 Sam 2:1/Ps 92:10 (Hannah's prayer; a horn-exaltation psalm) — no direct head-dress-oil relation established."),
    (775, "assoc", "1 Chr 13:7/2 Sam 6:3 (the ark at Abinadab's house; an unrelated cart narrative) — no clear Abinadab-Ephratah connection in the cited text."),
    (776, "narrower:a", "1 Sam 9:9 explains 'seer' as the older term for what became known as 'prophet,' and 1 Chr 29:29 names Nathan specifically as a prophet whose records were kept — Nathan is a specific instance of the seer/prophet role."),
    (777, "assoc", "1 Chr 15:19/25:1 show Ethan appointed as a Levitical musician — person-practice relation, matching the Asaph/Music pattern."),
    (778, "assoc", "1 Sam 14:25/Exod 3:8 (honey found in a forest; the deliverance promise) — unrelated content, no clean forest-prophecy relation."),
    (779, "assoc", "1 Kgs 2:25/2 Sam 8:18 connect Jehoiada (Benaiah's father) to the Cherethite-commanding context indirectly, matching the Jehoiada/Pelethites pattern."),
    (780, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (781, "part_of:a", "1 Kgs 5:8/6:15 describe cedar boards used to build the temple house's interior, matching the established cedar-as-building-material pattern."),
    (782, "assoc", "Ezek 27:5/1 Kgs 5:1 show Hiram supplying fir/cypress wood, matching the Cedar/Hiram and Algum/Hiram provider-resource pattern."),
    (783, "assoc", "2 Kgs 18:18/1 Kgs 4:3 use recorder and scribes as overlapping administrative-official roles, siblings."),
    (784, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (785, "assoc", "1 Chr 6:4/Josh 24:33 place Abishua in Eleazar's priestly genealogical line — genealogical, not hierarchy."),
    (786, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (787, "part_of:a", "1 Kgs 6:19/6:16 describe the oracle (inner sanctuary/Most Holy Place) as a specific architectural part of Solomon's temple."),
    (788, "part_of:a", "1 Kgs 8:22/2 Kgs 11:14 place the altar as a furnishing within Solomon's temple complex, matching the general temple-furnishing pattern."),
    (789, "assoc", "Ezek 27:6/Gen 10:4 (unrelated Bashan-oak material; Tarshish among Javan's descendants) — evidence too weak/mismatched for a clean island-Tarshish containment claim."),
    (790, "assoc", "1 Kgs 14:15/2 Kgs 15:29 (a reed-shaken metaphor; an unrelated Assyrian invasion notice) — no clean cane-Isaiah relation established."),
    (791, "assoc", "2 Kgs 6:17/Zech 1:8 (Elisha's fiery-chariot vision; Zechariah's colored-horses vision) — unrelated visions, coordinate imagery at best."),
    (792, "assoc", "1 Kgs 19:11/Exod 24:18 (Elijah's earthquake theophany; Moses entering a cloud) — unrelated narratives, no clean earthquake-hill relation."),
    (793, "assoc", "Jer 28:10/1 Kgs 22:11 show Hananiah's yoke-breaking sign occurring during Zedekiah's reign — temporal co-occurrence, not hierarchy."),
    (794, "assoc", "2 Kgs 8:16/3:1 place Elijah's ministry within Jehoram's reign — contemporary figures, matching the Amos/Uzziah pattern."),
    (795, "assoc", "1 Chr 28:18/Ps 18:10 use the cherub-chariot as a poetic theophany image — not a hierarchy or part-of relation between the concepts themselves."),
    (796, "assoc", "Amos 1:1/Hos 1:1 place Amos's ministry within Jeroboam II's reign — temporal co-occurrence, matching the Amos/Uzziah pattern."),
    (797, "assoc", "Ezra 4:2/2 Kgs 17:24 reflect the Samaritans' complex mixed-population origin from the former Kingdom of Israel's territory — too complex a historical relation to reduce to a clean hierarchy from this evidence."),
    (798, "assoc", "Hab 1:8/Jer 5:6 list leopard and lion as coordinate predatory-animal judgment images, matching the Lions/Wolf pattern."),
    (799, "assoc", "2 Kgs 18:17/Isa 36:2 connect the conduit to Hezekiah's Gihon-spring engineering project — an engineering-and-source relation, not composition."),
    (800, "assoc", "2 Kgs 18:18/2 Chr 34:8 mention Hilkiah near an unrelated recorder-office reform note — no evidence Hilkiah held the recorder's office."),
    (801, "assoc", "2 Chr 34:8/2 Sam 8:16 name a different individual (Jehoshaphat) as recorder under David — this evidence doesn't establish Joah specifically as recorder."),
    (802, "assoc", "2 Kgs 18:18/2 Chr 34:8 list Eliakim and Joah as coordinate officials in the same delegation, siblings."),
    (803, "assoc", "Isa 40:6/37:27 — the cited verse (37:27) doesn't carry the famous grass-flower part-whole imagery from Isa 40:7-8, so associated is the disciplined choice given the actual evidence shown."),
    (804, "assoc", "2 Chr 34:20/Jer 26:24 place Achbor and Gedaliah among Josiah-era/Shaphan-family court officials, coordinate."),
    (805, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (806, "assoc", "1 Chr 3:19/Hag 2:4 co-list Hananiah and Jeshua-era names in a post-exilic genealogy."),
    (807, "assoc", "Hag 1:1/1 Chr 3:19 co-list Jeshua and Meshullam among post-exilic/genealogical names."),
    (808, "assoc", "1 Chr 25:1/6:39 record Berechiah as Asaph's kinsman — genealogical, not hierarchy."),
    (809, "assoc", "1 Chr 25:1/6:44 list Asaph and Ethan as sibling Levitical musicians, coordinate."),
    (810, "assoc", "Ezra 7:1/1 Chr 9:11 co-list Ezra-era and Meshullam-lineage names in a priestly genealogy."),
    (811, "assoc", "1 Chr 29:7/Ezra 2:69 use daric and dram as near-synonymous ancient coin-unit terms, siblings."),
    (812, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (813, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (814, "assoc", "Ezra 3:2/Hag 1:1 show Jeshua rebuilding the altar 'as written in the Law of Moses' — the book covers the topic, not a hierarchy."),
    (815, "assoc", "Ps 102:6/Mic 1:8 list owl-adjacent desert imagery and dragon (jackal) as coordinate desolate-place creature terms."),
    (816, "assoc", "Hos 14:6/Ps 52:8 use cedar and olive-tree as parallel poetic flourishing images, not hierarchy."),
    (817, "assoc", "Prov 1:17/7:23 show a fowler hunting birds — practitioner-prey relation, matching the Hunting/Lions pattern."),
    (818, "assoc", "Dan 11:7/Isa 11:1 apply the messianic 'Branch' prophecy-title to Christ — a theological identification this vocabulary has no verb for, matching the Christ/Prophecy fallback."),
    (819, "assoc", "No verse evidence was recovered for this pair — kept as associated per the no-evidence-no-upgrade rule."),
    (820, "assoc", "Isa 35:1/40:3 describe a highway built through the desert — a route-through relation, not structural composition."),
    (821, "assoc", "Ezek 27:6/Isa 2:13 list box-tree and cedar as coordinate construction-wood types, siblings."),
    (822, "assoc", "Isa 42:1/53:11 connect covenant-faithfulness themes to a later Reformed doctrinal category (perseverance of the saints) this vocabulary has no verb for — a theological-doctrine relation, associated is the honest fallback."),
]


def main():
    judgments = []
    for idx, code, just in DECISIONS:
        p = BATCH[idx]
        a_id, b_id = p["a"]["id"], p["b"]["id"]
        entry = {"pair": [a_id, b_id], "justification": just}
        if code == "assoc":
            entry["verb"] = "associated"
        elif code == "contrasts":
            entry["verb"] = "contrasts"
        else:
            verb, side = code.split(":")
            first, second = (a_id, b_id) if side == "a" else (b_id, a_id)
            entry["verb"] = verb
            if verb == "narrower":
                entry["narrower"], entry["broader"] = first, second
            elif verb == "causes":
                entry["cause"], entry["effect"] = first, second
            elif verb == "part_of":
                entry["part"], entry["whole"] = first, second
        judgments.append(entry)

    out = {
        "batch_file": "phase5-batch-2026-09-26-w10.json",
        "model": "claude-in-session (Sonnet 5) — chunk 5 (final) of the weight>=10 batch (indices 600-822)",
        "judgments": judgments,
    }
    out_path = os.path.join(ROOT, "outputs", f"phase5-judgments-{date.today().isoformat()}-w10-chunk5.json")
    json.dump(out, open(out_path, "w"), indent=2, ensure_ascii=False)
    print(f"Wrote {len(judgments)} judgments to {out_path}")


if __name__ == "__main__":
    main()
